### PR TITLE
Add description getter on SingleEditionMintable

### PR DESCRIPTION
**Pull request by alexanderattar**
- PR for https://github.com/ourzora/nft-editions/issues/18
- Adds description getter
- Updates test to check for description
- Tidy package.json
- Bumps the typechain version

### CODE REVIEW

**Comment by iainnash** [comment]
This looks great! One thing I'd give feedback for is what would your thought be to instead make the description `string public description` and just make the getter name `description` like what we have for other getters in the contract.

**Comment by iainnash** [comment]
If you want to remove the change since it's been merged in for the getter I'd be happy to merge in the `package.json` updates.

**Comment by iainnash** [comment]
Closing this out since the getter part is already done :).

**Comment by alexanderattar** [comment]
Sorry I was traveling during the holidays. Got a bit behind and missed this thread! Thanks for the feedback and glad ya got it sorted already!

**Pull request closed without merging**
